apiVersion: v1
kind: Service
metadata:
  name: wwHotel-service
spec:
  selector:
    app: wwHotel
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      nodePort: 30011
  type: NodePort
